import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Nav from "./../../components/nav/nav";
import Header from "./../../components/header/header";
import classes from "./layout.module.css";
const geistSans = Poppins({
  variable: "--font-poppins",
  weight: "300",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${classes.container}`}>
        <div className={classes.header}>
          <Header />
        </div>
        <div className={classes.nav}>
          <Nav />
        </div>
        <div className={classes.bodyWrapper}>{children}</div>
      </body>
    </html>
  );
}
